---
abstract: 'Perl module for http plan output for structured errors.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Pure-HTTP
no_index:
  directory:
    - inc
    - t
requires:
  Error::Pure::Output::Text: 0.08
  Error::Pure::Utils: 0.08
  List::MoreUtils: 0
  Readonly: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Error-Pure-HTTP
  homepage: https://github.com/tupinek/Error-Pure-HTTP
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Error-Pure-HTTP
version: 0.01
